<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RuntimeIdentifier Condition="'${Configuration}' == 'release'">win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.FileSystem" />
    <PackageReference Include="Arbor.Aesculus" />
    <PackageReference Include="Arbor.KVConfiguration.JsonConfiguration" />
    <PackageReference Include="Arbor.KVConfiguration.Schema.Json" />
    <PackageReference Include="Arbor.KVConfiguration.UserConfiguration" />
    <PackageReference Include="Arbor.KVConfiguration.Core" />
    <PackageReference Include="Arbor.Processing" />
    <PackageReference Include="Arbor.Sorbus" />
    <PackageReference Include="Arbor.Tooler" />
    <PackageReference Include="Autofac" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence" />
    <PackageReference Include="Microsoft.Web.Xdt" />
    <PackageReference Include="Microsoft.Windows.Compatibility" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Tools\Scripts\" />
  </ItemGroup>

</Project>
