//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbor.Build.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arbor.Build.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content files full path is null.
        /// </summary>
        internal static string ContentFullPathIsNull {
            get {
                return ResourceManager.GetString("ContentFullPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any exe files to merge.
        /// </summary>
        internal static string CouldNotFindAnyExeFileToMerge {
            get {
                return ResourceManager.GetString("CouldNotFindAnyExeFileToMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get Visual Studio path.
        /// </summary>
        internal static string CouldNotGetVisualStudioPath {
            get {
                return ResourceManager.GetString("CouldNotGetVisualStudioPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions must start with &apos;.&apos;, eg .txt.
        /// </summary>
        internal static string FileExtensionMustStartWithDot {
            get {
                return ResourceManager.GetString("FileExtensionMustStartWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immutable array cannot be default.
        /// </summary>
        internal static string ImmutableArrayCannotBeDefault {
            get {
                return ResourceManager.GetString("ImmutableArrayCannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch name could not be found.
        /// </summary>
        internal static string TheBranchNameCouldNotBeFound {
            get {
                return ResourceManager.GetString("TheBranchNameCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the branch name after asking Git.
        /// </summary>
        internal static string TheBranchNameCouldNotBeFoundByAskingGit {
            get {
                return ResourceManager.GetString("TheBranchNameCouldNotBeFoundByAskingGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nuget package does {0} not contain any nuspec.
        /// </summary>
        internal static string TheNuGetPackageIsMissingANuSpec {
            get {
                return ResourceManager.GetString("TheNuGetPackageIsMissingANuSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temp path contains invalid characters.
        /// </summary>
        internal static string ThePathContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("ThePathContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        internal static string ValueCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhitespace", resourceCulture);
            }
        }
    }
}
