name: Sonar

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        cache: true
        cache-dependency-path: tests/Arbor.Build.Tests.Integration
    - name: Install SonarCloud scanner
      shell: pwsh
      run: |
        dotnet tool install --global dotnet-sonarscanner
    - name: Start sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: pwsh
      run: |
          $ErrorActionPreference = "Stop"
          $PSNativeCommandUseErrorActionPreference = $true
          if ([string]::IsNullOrWhiteSpace($env:SONAR_TOKEN)) { throw "SONAR_TOKEN is empty or not configured" }
          dotnet sonarscanner begin /k:"niklaslundberg_Arbor.Build" /o:"niklaslundberg" /d:sonar.token="$env:SONAR_TOKEN" "/d:sonar.cs.opencover.reportsPaths=$($pwd)\Artifacts\TestReports\Coverage\*.opencover.xml" "/d:sonar.cs.vstest.reportsPaths=$($pwd)\Artifacts\TestReports\Tests\*.trx" /d:sonar.verbose=true
          dotnet build Arbor.Build.sln
          Get-ChildItem -Path tests -Recurse -Filter *.csproj | ForEach-Object { $fileName = $_.FullName; $name = $_.Name; dotnet test $fileName /p:CollectCoverage=true /p:CoverletOutputFormat=opencover "/p:CoverletOutput=$($pwd)\Artifacts\TestReports\Coverage\$($name).opencover.xml" --logger "trx;LogFileName=$($pwd)\Artifacts\TestReports\Tests\$($name).trx" }
          Get-ChildItem -Recurse -Directory | select-object FullName
          dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN" /d:sonar.verbose=true
